blank_issues_enabled: true

# Update url below as needed. 
contact_links:
  - name: GitHub Discussions
    url: https://github.com/Keyfactor/signserver-ce/discussions
    about: Join in-depth discussions or ask questions
