name: test-signing

on:
 workflow_dispatch:
 push:
  branches: [update-to-support-more-workers]

jobs:
  start-container:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
       
    - name: Start SignServer Container
      run: sudo docker run -d -it --rm --name signserver -p 80:8080 -p 443:8443 -e LOG_LEVEL_APP=DEBUG -v /home/runner/work/signserver-signing-action/signserver-signing-action/testing/ManagementCA.cacert.crt:/mnt/external/secrets/tls/cas/ManagementCA.crt -h localhost keyfactor/signserver-ce:6.2.0  
          
    - name: Wait for Container to deploy
      run: sleep 180s
      shell: bash
