name: test-PDFSigner

on:
 workflow_dispatch:

jobs:
 sign-pdf:
  runs-on: ubuntu-latest
  steps:
  - name: Sign PDF
    id: sign-file
    uses: ./
    with:
     endpoint: http://localhost:80/signserver
     file-path: /home/runner/work/signserver-signing-action/signserver-signing-action/testing/sample.pdf
     worker-name: PDFSigner
     output-file-name: sample-signed.pdf
